global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "gateway-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["192.168.200.128:8080"]

  - job_name: "auth-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["192.168.200.128:8081"]

  - job_name: "permission-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["192.168.200.128:8082"]

# 说明：本配置默认抓取虚拟机上的服务，若服务容器化需改为容器服务名
